services:
  app:
    container_name: lycet-app
    build:
      context: .
      target: dev
    ports:
      - '${APP_PORT:-8000}:8000'
    volumes:
      - './data:/var/www/html/data'
    environment:
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET:-changeme}
      CLIENT_TOKEN: ${CLIENT_TOKEN:-123456}
      SOL_USER: ${SOL_USER:-20161515648MODDATOS}
      SOL_PASS: ${SOL_PASS:-MODDATOS}
      FE_URL: ${FE_URL:-https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService}
      RE_URL: ${RE_URL:-https://e-beta.sunat.gob.pe/ol-ti-itemision-otroscpe-gem-beta/billService}
      GUIA_URL: ${GUIA_URL:-https://e-beta.sunat.gob.pe/ol-ti-itemision-guia-gem-beta/billService}
      AUTH_URL: ${AUTH_URL:-https://gre-test.nubefact.com/v1}
      API_URL: ${API_URL:-https://gre-test.nubefact.com/v1}
      CLIENT_ID: ${CLIENT_ID:-test-85e5b0ae-255c-4891-a595-0b98c65c9854}
      CLIENT_SECRET: ${CLIENT_SECRET:-test-Hty/M6QshYvPgItX2P0+Kw==}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN:-.}
      TRUSTED_PROXIES: '127.0.0.1,REMOTE_ADDR'
