name: Promote to Production

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish Docker Image"]
    types: [completed]

jobs:
  deploy-production:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push') }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
